# Generated by Django 5.2.3 on 2025-06-19 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200, verbose_name='Città/Paese di ritrovo')),
                ('location_link', models.CharField(blank=True, help_text='Link del ritrovo', max_length=500, null=True)),
                ('maps_link', models.URLField(blank=True, help_text='Link al percorso su Maps (opzionale)', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, upload_to='eventImages/')),
                ('event_type', models.CharField(choices=[('statico', 'Motoraduni statici'), ('itinerante', 'Motoraduni itineranti'), ('motogiro', 'Motogiri'), ('enogastronomico', 'Moto Tour Enogastronomici'), ('trackday', 'Trackday')], default='statico', max_length=20, verbose_name='Tipo di evento')),
                ('registration_start', models.DateTimeField(help_text='Quando si aprono le iscrizioni', verbose_name='Inizio iscrizioni')),
                ('registration_end', models.DateTimeField(help_text='Quando scadono le iscrizioni', verbose_name='Fine iscrizioni')),
                ('is_cancelled', models.BooleanField(default=False, help_text="Se l'organizzatore ha cancellato l'evento", verbose_name="Annullato dall'organizzatore")),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizzatore')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('confirmed', 'Confermata'), ('cancelled', 'Annullata')], default='pending', max_length=20, verbose_name='Stato iscrizione')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partecipazione',
                'verbose_name_plural': 'Partecipazioni',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
