# Generated by Django 5.2.3 on 2025-06-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='num_participates',
            field=models.PositiveIntegerField(default=1, help_text='Numero totale di partecipanti (utente + ospiti)'),
        ),
    ]
