# Generated by Django 5.2.3 on 2025-06-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('event', '0002_participation_num_participates'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='motorcycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partecipazioni', to='accounts.motorcycle', verbose_name='Moto del partecipante'),
        ),
    ]
