# Generated by Django 5.2.3 on 2025-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_participation_motorcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='guests',
            field=models.JSONField(blank=True, default=list, help_text='Lista accompagnatori in formato JSON'),
        ),
    ]
