# Generated by Django 5.2.3 on 2025-06-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_participation_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='guests',
        ),
    ]
