# Generated by Django 5.2.3 on 2025-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_participation_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('statico', 'Motoraduni statici'), ('motogiro', 'Motogiri'), ('enogastronomico', 'Moto Tour Enogastronomici'), ('trackday', 'Trackday')], default='statico', max_length=20, verbose_name='Tipo di evento'),
        ),
    ]
