# Generated by Django 5.2.3 on 2025-06-18 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_participation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Partecipazione', 'verbose_name_plural': 'Partecipazioni'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text="Se l'organizzatore ha cancellato l'evento", verbose_name="Annullato dall'organizzatore"),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitudine'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitudine'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizzatore'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Quando scadono le iscrizioni', verbose_name='Fine iscrizioni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Quando si aprono le iscrizioni', verbose_name='Inizio iscrizioni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('confirmed', 'Confermata'), ('cancelled', 'Annullata')], default='pending', max_length=20, verbose_name='Stato iscrizione'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to=settings.AUTH_USER_MODEL),
        ),
    ]
