# Generated by Django 5.2.3 on 2025-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_participation_options_event_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.AddField(
            model_name='event',
            name='location_link',
            field=models.CharField(blank=True, help_text='Link del ritrovo', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Città/Paese di ritrovo'),
        ),
    ]
