# Generated by Django 5.2.3 on 2025-06-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_event_latitude_remove_event_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maps_link',
            field=models.URLField(blank=True, help_text='Link al percorso su Maps (opzionale)', max_length=500, null=True),
        ),
    ]
