# Generated by Django 5.2.3 on 2025-06-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_cancelled',
            new_name='is_annulled',
        ),
    ]
