# Generated by Django 5.2.3 on 2025-06-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_is_cancelled_event_is_annulled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eventImages/'),
        ),
    ]
