# Generated by Django 5.2.3 on 2025-06-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_link',
            field=models.CharField(blank=True, help_text='Link del ritrovo', max_length=500, null=True),
        ),
    ]
