# Generated by Django 5.2.3 on 2025-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maps_link',
            field=models.URLField(blank=True, help_text='Link al percorso su Maps (opzionale)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
