# Generated by Django 5.2.3 on 2025-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_maps_link_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('statico', 'Motoraduni statici'), ('itinerante', 'Motoraduni itineranti'), ('motogiro', 'Motogiri'), ('enogastronomico', 'Moto Tour Enogastronomici'), ('trackday', 'Trackday')], default='statico', max_length=20, verbose_name='Tipo di evento'),
        ),
    ]
